# Application-level settings (see https://developer.wildernesslabs.co/Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/)
Lifecycle:
    RestartOnAppFailure: true
    AppFailureRestartDelaySeconds: 15

Logging:
    LogLevel:
        Default: "Information"

# Custom app settings. These flatten to dot-notated keys in App.Settings,
# e.g. this resolves to Settings["App.DeviceName"].
App:
    DeviceName: Monsterbox-v1
