### Monsterbox Maple server endpoints
### Edit @host below to match the device's IP (see boot log / Resolver.Log output for "WiFi connected. IP: ...")
@host = 192.168.1.100:5417

### Play sound file 1 for 5 seconds
POST http://{{host}}/sound?filenumber=1&fileduration=5

### Play sound file 3 for 10 seconds
POST http://{{host}}/sound?filenumber=3&fileduration=10

### Shake with default configuration (25-50 iterations, 50-75ms delay)
POST http://{{host}}/shake

### Shake with a short, gentle run
POST http://{{host}}/shake?bi=5&ei=10&bd=100&ed=150

### Shake with a long, aggressive run
POST http://{{host}}/shake?bi=75&ei=100&bd=25&ed=40
